### ISSUE TITLE
Can we apply GPLv3 license to source codes which utilize RPostgreSQL?

### ISSUE THREAD

**Issue by YTs63** [tomoakin/RPostgreSQL#104]
We are currently developing an application using R language and in that application, we use OSS libraries under GPLv3 (e.g. Matrix, tidyselect). And we also would like to use RPostgreSQL.
 But RPostgreSQL is published under GPLv2. Could you possibly give us a permission to use RPostgreSQL in combination with our application whichi utilizes OSS Under GPLv3?

**Comment by tomoakin** [comment]
The license is now changed to GPLv3 after communicating with the original authors via e-mails.
