### ISSUE TITLE
Outdated config.guess and config.sub

### ISSUE THREAD

**Issue by Roenbaeck** [tomoakin/RPostgreSQL#111]
The provided config.guess and config.sub are from 2011 and fails to recognise many new systems/architectures. The error message suggests downloading a newer version:

> This script, last modified 2011-10-19, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

>  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
> and
>  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

> If the version you run (src/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

Visiting the links above, the newer files where last updated 2020-04-26. I think it would be great if you could switch to these.

**Comment by rolweber** [comment]
The last commit to this project was [two years ago](https://github.com/tomoakin/RPostgreSQL/commits/master).
And PRs have [not been merged](https://github.com/tomoakin/RPostgreSQL/pulls) for years either.

Looks like this project is abandoned.

**Comment by tomoakin** [comment]
Copied a new one with commit: 5e77a2ed18b2a00a4d6dc483b69317e8e506b0e9
