### ISSUE TITLE
** CONSIDER USING THE `RPostgres` PACKAGE INSTEAD **

### ISSUE THREAD

**Issue by warnes** [tomoakin/RPostgreSQL#135]
This package (`RPostgreSQL`) seems to be on life support, with no major changes or responses to support requests in the last year.

The [`RPostgres`](https://github.com/r-dbi/RPostgres)  package appears to be actively maintained, and resolves some of the issues I've encountered in `RPostgreSQL`.

See https://github.com/r-dbi/RPostgres

**Comment by helmingstay** [comment]
Thanks, this was my question. The only other place I could find that mentions both in the same place was the CRAN Database task view, but it doesn't offer any comparison (https://cran.r-project.org/web/views/Databases.html).

**Comment by tomoakin** [comment]
This is not an appropriate place to write this though.
