### ISSUE TITLE
setting up travis ci

### ISSUE THREAD

**Issue by jangorecki** [tomoakin/RPostgreSQL#77]
I've manage to successfully setup postgres on travis-ci so it can be consumed from R tests.
Originally I've setup one a while ago here [logR/.travis.yml](https://github.com/jangorecki/logR/blob/master/.travis.yml)
[This](https://travis-ci.org/jangorecki/RPostgreSQL/builds/84989866) is the successful build for your current latest version, reorganized in [reorg_pkg](https://github.com/jangorecki/RPostgreSQL/tree/reorg_pkg) just by putting all the objects from root dir to `inst/misc`. The travis related commits are in [travis](https://github.com/jangorecki/RPostgreSQL/tree/travis) branch.
If you are willing to reorganize dir structure I can PR both branches.

**Comment by tomoakin** [comment]
travis ci was now set up. Because we keep a subtree that go to CRAN and that do not go but used for testing, the directory is not reorganized.
