### ISSUE TITLE
install_github from devtools does not work.

### ISSUE THREAD

**Issue by iangow** [tomoakin/RPostgreSQL#82]
```
> devtools::install_github("tomoakin/RPostgreSQL")
Downloading GitHub repo tomoakin/RPostgreSQL@master
from URL https://api.github.com/repos/tomoakin/RPostgreSQL/zipball/master
Error: Does not appear to be an R package (no DESCRIPTION)
```

**Comment by jangorecki** [comment]
You need to point to subdirectory in that github repository, package is not placed in top level dir. You should look at `install_github` manual.

**Comment by iangow** [comment]
OK, so `devtools::install_github("tomoakin/RPostgreSQL", subdir="RPostgreSQL")` works. Perhaps that could be mentioned in a `README.md` on main repository page (assuming there are good reasons for package not to be in a top-level directory).

Thanks.
